// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_score_100 = "CgkIyqv0lcUPEAIQAA"; // <GPGSID>
        public const string achievement_score_250 = "CgkIyqv0lcUPEAIQAg"; // <GPGSID>
        public const string achievement_score_1500 = "CgkIyqv0lcUPEAIQBw"; // <GPGSID>
        public const string achievement_score_10000 = "CgkIyqv0lcUPEAIQCg"; // <GPGSID>
        public const string achievement_score_5000 = "CgkIyqv0lcUPEAIQCQ"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIyqv0lcUPEAIQBA"; // <GPGSID>
        public const string achievement_score_1000 = "CgkIyqv0lcUPEAIQBg"; // <GPGSID>
        public const string achievement_score_3000 = "CgkIyqv0lcUPEAIQCA"; // <GPGSID>
        public const string achievement_score_500 = "CgkIyqv0lcUPEAIQBQ"; // <GPGSID>
        public const string achievement_score_50 = "CgkIyqv0lcUPEAIQAQ"; // <GPGSID>

}

